version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'         
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm install -f --legacy-peer-deps
            npm install @angular/http --legacy-peer-deps
      - run:
          name: Front-End Build
          command: |
            npm run build
  test-app:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm install -f --legacy-peer-deps
            npm install @angular/http --legacy-peer-deps
      - run:
          name: Test App
          command: |
            npm run test
  lint:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            npm install -f --legacy-peer-deps
            npm install @angular/http --legacy-peer-deps
      - run:
          name: Lint App Code
          command: |
            npm run lint
  test-e2e:
    docker:
      - image: "cimg/node:14.15-browsers"
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 100.0.4896.20
      - browser-tools/install-chromedriver
      - run:
          name: Install Front-End Dependencies
          command: |
            npm install -f --legacy-peer-deps
            npm install @angular/http --legacy-peer-deps
      - run:
          name: End to End Test
          command: |
            npm run e2e
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15' 
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          command: |
            npm run deploy
  test-backend-connection:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Test App Connection To Backend
          command: |
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $WEB_SERVER_DNS)
            (( $STATUS_CODE=="200" )); echo $?


workflows:
  udagram-frontend:
    jobs:
      - build
      - test-app:
          requires:
            - build
      - lint:
          requires:
            - build      
      - test-e2e:
          requires:
            - build      
      - deploy:
          context:
            Udgram
          requires:
            - test-app
            - lint
            - test-e2e
      - test-backend-connection:
          requires:
            - deploy